### ISSUE TITLE
Received LOOSING_MOVE for no reason

### ISSUE THREAD

**Issue by Madour** [Tybau/snakeotron#5]
* Difficulty 3

![image](https://user-images.githubusercontent.com/11854124/70395441-f1f56400-19fe-11ea-86a9-e86f8fabe768.png)

As you can see, sendMove(SOUTH) returned LOSING_MOVE even though there are no walls/snake in south direction.
This bug happened a few times on this map, maybe it is because of the seed (i don't have it)?

**Comment by Tybau** [comment]
The walls around spawn points were not removal on two cases.
