### ISSUE TITLE
getSnakeArena blocks the program

### ISSUE THREAD

**Issue by leboulec** [Tybau/snakeotron#6]
Here are the info of the game
"SUPER_PLAYER difficulty=3 timeout=100 start=1 seed=5618287"

The program blocks at line 112 in clientApi.c (r = read(sockfd, stream_size, HEAD_SIZE); )

This happens in several games, particularly with difficulty=3

**Comment by thilaire** [comment]
I am aware of this issue, that do not happen in my machine (but in the server used for our contest). I will soon propose a fix

**Comment by thilaire** [comment]
The bug is now removed (by commit 06fa185)
Thanks for the report (with appropriate data)
